"""Central configuration for HW1 piano transcription experiments."""

# Audio / label setup
SAMPLE_RATE = 16000
MIN_MIDI = 21
MAX_MIDI = 108
N_PIANO_KEYS = 88

# Spectrogram setup
HOP_SIZE = 512
N_MELS = 229
N_FFT = 2048
F_MIN = 30
F_MAX = 8000

# Metric thresholds
FRAME_THRESHOLD = 0.5
ONSET_THRESHOLD = 0.5

# Experiment defaults
DEFAULT_DATASET_PATH = "gct731-maestro"
DEFAULT_MODEL_NAME = "basic"
DEFAULT_BATCH_SIZE = 16
DEFAULT_SEQUENCE_LENGTH = 102400
DEFAULT_NUM_EPOCHS = 10
DEFAULT_STEPS_PER_EPOCH = 1000
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_WEIGHT_DECAY = 0.0
DEFAULT_CNN_UNIT = 24
DEFAULT_FC_UNIT = 64
DEFAULT_RNN_UNIT = 64
DEFAULT_NUM_WORKERS = 0
DEFAULT_SEED = 42
DEFAULT_SAVE_DIR = "experiments"
