defaults:
  - model: basic
  - wandb_usage: enabled
  - _self_

seed: 42
device: cuda
gpu_ids: null

experiment:
  name: ${model.name}_${now:%Y%m%d_%H%M%S}

data:
  path: gct731-maestro
  train_split: train
  valid_split: validation
  sequence_length: 102400
  batch_size: 16
  num_workers: 0

optimization:
  epochs: 10
  steps_per_epoch: 1000
  learning_rate: 1e-3
  min_learning_rate: 0.0
  weight_decay: 0.0
  offset_loss_weight: 1.0

save:
  root_dir: experiments
  save_every_epoch: false

hydra:
  job:
    chdir: false
  run:
    dir: ${save.root_dir}/${experiment.name}
  sweep:
    dir: ${save.root_dir}/multirun/${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}_${experiment.name}
